//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BearingIns.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DIALOG_RECT                 101
#define IDD_BEARINGINS_DIALOG           102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_CTRLMODELMANAGE_DIALOG      130
#define IDD_DIALOG_MODEL                131
#define IDB_BITMAP_NOTSELECTED          131
#define IDB_BITMAP_SELECTED             132
#define IDD_DIALOG_SETUP                133
#define IDD_DIALOG_PROCESSING           134
#define IDD_DIALOG_SETUP_MODEL          135
#define IDD_DIALOG_SETUP_TEACHING       136
#define IDD_DIALOG_SETUP_ALIGN          137
#define IDD_DIALOG_SETUP_LIGHT          138
#define IDD_DIALOG_SETUP_SYSTEM         139
#define IDC_STATIC_MAIN_DISP            1000
#define IDC_BTNENHCTRL_LIVE             1001
#define IDC_BTNENHCTRL_SAVE             1002
#define IDC_BTNENHCTRL_LOAD             1003
#define IDC_BTNENHCTRL_ZOOM_IN          1004
#define IDC_BTNENHCTRL_ZOOM_OUT         1005
#define IDC_BTNENHCTRL_ZOOM_11          1006
#define IDC_BTNENHCTRL_ZOOM_FIT         1007
#define IDC_STATIC_NG_DISP1             1008
#define IDC_STATIC_NG_DISP2             1009
#define IDC_STATIC_NG_DISP3             1010
#define IDC_SCROLLBAR_NG_DISPLAY        1011
#define IDC_BTNENHCTRL_RUN              1012
#define IDC_BTNENHCTRL_SETUP            1013
#define IDC_BTNENHCTRL_MODEL            1014
#define IDC_BTNENHCTRL_EXIT             1015
#define IDC_LIST1                       1016
#define IDC_LIST_STATUS                 1016
#define IDC_LIST_INSP                   1016
#define IDC_BTNENHCTRL_MODEL_NAME       1017
#define IDC_BTNENHCTRL_MODEL_WIDTH      1018
#define IDC_BTNENHCTRL_MODEL_HEIGHT     1019
#define IDC_BTNENHCTRL_MODEL_BEARING_CNT 1020
#define IDC_BTNENHCTRL_MODEL_PI         1022
#define IDC_BTNENHCTRL_RESULT_TITLE     1023
#define IDC_SCROLLBAR_MAIN_V            1024
#define IDC_SCROLLBAR_MAIN_H            1025
#define IDC_BTNENHCTRL_MODEL_NEW        1026
#define IDC_BTNENHCTRL_MODEL_DELETE     1027
#define IDC_BTNENHCTRL_MODEL_SELECT     1028
#define IDC_PROGRESS_PROCESS            1029
#define IDC_EDIT_MODEL_WIDTH            1030
#define IDC_EDIT_MODEL_HEIGHT           1031
#define IDC_EDIT_MODEL_CNT              1032
#define IDC_EDIT_MODEL_PI               1033
#define IDC_STATIC_GROUP_MODEL          1034
#define IDC_TAB_SETUP_MENU              1035
#define IDC_EDIT_MODEL_GAP              1035
#define IDC_BTNENHCTRL_CANCEL           1036
#define IDC_EDIT_MODEL_PIXEL_SIZE       1036
#define IDC_BTNENHCTRL_OK               1037
#define IDC_EDIT_SCORE                  1037
#define IDC_EDIT_MODEL_DIAMETER         1037
#define IDC_BTNENHCTRL_APPLY            1038
#define IDC_EDIT_THRD                   1038
#define IDC_EDIT_MODEL_COL              1038
#define IDC_EDIT_SCORE2                 1038
#define IDC_BTNENHCTRL_TEACH            1040
#define IDC_BTNENHCTRL_TEST             1041
#define IDC_BTNENHCTRL_UP               1042
#define IDC_BTNENHCTRL_DOWN             1043
#define IDC_BTNENHCTRL_LEFT             1044
#define IDC_BTNENHCTRL_RIGHT            1045
#define IDC_EDIT_MOVE_CNT               1046
#define IDC_BTNENHCTRL_ALL_TEACH        1047
#define IDC_BTNENHCTRL_CALCUL_GAP       1048
#define IDC_BTNENHCTRL_SCALE_UP         1048
#define IDC_BTNENHCTRL_TEACHING_GRAB    1049
#define IDC_BUTTON_TEST                 1050
#define IDC_BTNENHCTRL_SCALE_DOWN       1050
#define IDC_EDIT_SCALE                  1051
#define IDC_SLIDER_LIGHT_0              1057
#define IDC_SLIDER_LIGHT_1              1058
#define IDC_SLIDER_LIGHT_2              1059
#define IDC_SLIDER_LIGHT_3              1060
#define IDC_EDIT_LIGHT_0                1061
#define IDC_EDIT_LIGHT_1                1062
#define IDC_EDIT_LIGHT_2                1063
#define IDC_EDIT_LIGHT_3                1064
#define IDC_EDIT_INSP_PARA_0            1065
#define IDC_EDIT_INSP_PARA_1            1066
#define IDC_EDIT_INSP_PARA_2            1067
#define IDC_BUTTON_TEST2                1070
#define IDC_BTNENHCTRLSTART             1071
#define IDC_BUTTON_OUT_0                1072
#define IDC_BUTTON1                     1073
#define IDC_BUTTON_MASTER_SAVE          1074
#define IDC_BTNENHCTRL_RESULT           1074
#define IDC_BUTTON_MASTER_LOAD          1075
#define IDC_RADIO_ALIGN_TYPE0           1075
#define IDC_RADIO_ALIGN_TYPE1           1076
#define IDC_EDIT_PARA_0                 1076
#define IDC_BUTTON_OUT_1                1077
#define IDC_EDIT_PARA_1                 1077
#define IDC_BUTTON_OUT_2                1078
#define IDC_EDIT_PARA_2                 1078
#define IDC_BUTTON_OUT_3                1079
#define IDC_EDIT_PARA_3                 1079
#define IDC_BUTTON_OUT_4                1080
#define IDC_BUTTON_PARA_ALL_0           1080
#define IDC_BUTTON_OUT_5                1081
#define IDC_BUTTON_PARA_ALL_1           1081
#define IDC_BUTTON_OUT_6                1082
#define IDC_BUTTON_PARA_ALL_2           1082
#define IDC_BUTTON_OUT_7                1083
#define IDC_BUTTON_PARA_ALL_3           1083
#define IDC_BUTTON_OUT_8                1084
#define IDC_BUTTON_PARA_ALL_4           1084
#define IDC_BUTTON_OUT_9                1085
#define IDC_BUTTON_PARA_ALL_5           1085
#define IDC_BUTTON_PARA_ALL_6           1086
#define IDC_BTNENHCTRL1                 1086
#define IDC_BUTTON_PARA_ALL_7           1087
#define IDC_BTNENHCTRL2                 1087
#define IDC_BTNENHCTRL3                 1088
#define IDC_BTNENHCTRL4                 1089
#define IDC_BTNENHCTRL5                 1090
#define IDC_BTNENHCTRL_TOTAL            1091
#define IDC_BTNENHCTRL_OK1              1092
#define IDC_BTNENHCTRL_NG1              1093
#define IDC_BTNENHCTRL_OK2              1094
#define IDC_BTNENHCTRL_NG2              1095
#define IDC_BTNENHCTRL_CNT_RESET        1096
#define IDC_CHECK1                      1097
#define IDC_CHECK2                      1098
#define IDC_CHECK_SAVE_0                1098
#define IDC_CHECK3                      1099
#define IDC_CHECK_SAVE_1                1099
#define IDC_STATIC_SCORE                1099
#define IDC_CHECK4                      1100
#define IDC_CHECK_SAVE_2                1100
#define IDC_CHECK5                      1101
#define IDC_CHECK_INSPECTION_3          1101
#define IDC_STATIC_BRIGHTNESS           1102
#define IDC_STATIC_X                    1103
#define IDC_CHECK_INSP_BROKEN           1103
#define IDC_STATIC_Y                    1104
#define IDC_EDIT_SYSTEM_HOUR            1104
#define IDC_EDIT_SYSTEM_MINUTE          1105
#define IDC_EDIT_SYSTEM_DAY             1106
#define IDC_CHECK_INSPECTION_0          1107
#define IDC_CHECK_INSPECTION_1          1108
#define IDC_CHECK_INSPECTION_2          1109
#define IDC_EDIT_NAME                   7000
#define IDC_EDIT_DESC                   7001
#define IDC_LIST_MODEL                  7002
#define IDC_BUTTON_NEW                  7003
#define IDC_BUTTON_DELETE               7004
#define IDC_BUTTON_SELECT               7005
#define IDC_BUTTON_OK                   7006
#define IDC_BUTTON_CANCEL               7007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1110
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
